# Document:
# http://simiki.org/docs/configuration.html

url: 
title: fredia的wiki
keywords: technology
description: 
author: fredia

root: /wiki

deploy:
        - type: git
          remote: origin
          branch: gh-pages


